---
- name: x510
  connection: network_cli
  hosts: x510
  collections:
    - alliedtelesis.awplus
  tasks:
    - name: Run openflow hidden commands
      awplus_command: 
        commands: show openflow appctl dpctl
      register: output

    - name: save output
      copy:
        content: "{{output.stdout[0]}}"
        dest: "$HOME/ansible-backups/{{inventory_hostname}}-of-output.txt"

      delegate_to: access_machine #specify which host to copy to
