---
- name: test for aw1
  connection: network_cli
  hosts: aw1
  collections:
    - alliedtelesis.awplus
  tasks:
    - name: run show running-config                         # task name
      awplus_command:                                       # module name
        commands: show running-config

- name: test for aw2
  connection: network_cli
  hosts: aw1
  collections:
    - alliedtelesis.awplus
  tasks:
    - name: run show running-config                         # task name
      awplus_command:                                       # module name
        commands: show running-config

