---
- name: x510
  connection: network_cli
  hosts: x510
  collections:
    - alliedtelesis.awplus
  tasks:
    # Save current config on the switch
    - name: run show running-config
      awplus_command:
        commands: show running-config
      register: config_before

    # Add openflow config
    - name: add openflow ports
      awplus_openflow:
        ports:
          - name: port1.0.25
            openflow: true

          - name: port1.0.13
            openflow: true

            #        controllers:
            #          - name: "con1"
            #            protocol: tcp
            #            address: 192.168.1.2
            #            ssl_port: 10
        state: present

        native_vlan: 4090

    # Save current config on the switch
    - name: run show running-config
      awplus_command:
        commands: show running-config
      register: config_after

    - name: save before config change
      copy:
        content: "{{config_before.stdout[0]}}"
        dest: "$HOME/ansible-backups/{{inventory_hostname}}-config-before.txt"

      delegate_to: access_machine #specify which host to copy to

    - name: save after config change
      copy:
        content: "{{config_after.stdout[0]}}"
        dest: "$HOME/ansible-backups/{{inventory_hostname}}-config-after.txt"

      delegate_to: access_machine #specify which host to copy to

    - name: Generate diff
      ansible.utils.fact_diff:
        before: "{{config_before.stdout[0]}}"
        after: "{{config_after.stdout[0]}}"
      register: diff_config

    - name: save diff file
      copy:
        content: "{{diff_config.stdout[0]}}"
        dest: "$HOME/ansible-backups/{{inventory_hostname}}-diff.txt"

      delegate_to: access_machine #specify which host to copy to

- name: x930
  connection: network_cli
  hosts: x930
  collections:
    - alliedtelesis.awplus
  tasks:
    # Save current config on the switch
    - name: run show running-config
      awplus_command:
        commands: show running-config
      register: config_before

    - name: add openflow ports
      awplus_openflow:
        #        controllers:
        #          - name: "con1"
        #            protocol: tcp
        #            address: 192.168.1.2
        #            ssl_port: 10
        state: present

        native_vlan: 4090

        ports:
          - name: port1.0.23
            openflow: true

          - name: port1.0.13
            openflow: true

    # Save current config on the switch
    - name: run show running-config
      awplus_command:
        commands: show running-config
      register: config_after

    - name: save before and after config change
      copy:
        content: "{{config_before.stdout[0]}}"
        dest: "$HOME/ansible-backups/{{inventory_hostname}}-config-before.txt"

      delegate_to: access_machine #specify which host to copy to

    - name: save before and after config change
      copy:
        content: "{{config_after.stdout[0]}}"
        dest: "$HOME/ansible-backups/{{inventory_hostname}}-config-after.txt"

      delegate_to: access_machine #specify which host to copy to

    - name: Generate diff
      command: diff "{{config_before.stdout[0]}}" "{{config_after.stdout[0]}}"
      register: diff_config

    - name: save diff file
      copy:
        content: "{{diff_config.stdout[0]}}"
        dest: "$HOME/ansible-backups/{{inventory_hostname}}-diff.txt"

      delegate_to: access_machine #specify which host to copy to

      #- name: access_machine
      #  hosts: access_machine
      #  tasks:
      #    - name: Generate diff
      #      command: diff $HOME/ansible-backups/x510-config-before.txt $HOME/ansible-backups/x510-config-after.txt
      #      register: config_diff
      #
      #    - name: save diff file
      #      copy:
      #        content: "{{config_diff.stdout[0]}}"
      #        dest: "$HOME/ansible-backups/x51-diff.txt"
      #
