---
- name: x510
  connection: network_cli
  hosts: x510
  collections:
    - alliedtelesis.awplus
  tasks:
    - name: Create an empty file
      file:
        path: "$HOME/ansible-backups/job-{{ awx_job_id }}"
        state: touch
      delegate_to: access_machine #specify which host

    - name: save job info in a file
      lineinfile:
        path: "$HOME/ansible-backups/job-{{ awx_job_id }}"
        line: |+
          "jobID: {{ awx_job_id }}
          launch_type: {{ awx_job_launch_type }}
          template_id: {{ awx_job_template_name }}
          project_revision: {{ awx_project_revision }}
          user_email: {{ awx_user_email }}
          firstname: {{ awx_user_first_name }}
          lastname: {{ awx_user_last_name }}
          userid: {{ awx_user_id }}
          username: {{ awx_user_id }}"
        insertbefore: BOF

      delegate_to: access_machine #specify which host to copy to
      ignore_errors: yes #ignore errors since some variables might not be applicable

    - name: save job info in a file
      lineinfile:
        path: "$HOME/ansible-backups/job-{{ awx_job_id }}"
        line: "schedule_id: {{ awx_schedule_id }}"
        insertbefore: BOF

      delegate_to: access_machine #specify which host to copy to
      ignore_errors: yes #ignore errors since some variables might not be applicable

    - name: save job info in a file
      lineinfile:
        path: "$HOME/ansible-backups/job-{{ awx_job_id }}"
        line: "schedule_name: {{ awx_schedule_name }}"
        insertbefore: BOF

      delegate_to: access_machine #specify which host to copy to
      ignore_errors: yes #ignore errors since some variables might not be applicable

    - name: save job info in a file
      lineinfile:
        path: "$HOME/ansible-backups/job-{{ awx_job_id }}"
        line: "workflow_jobid: {{ awx_workflow_job_id }}"
        insertbefore: BOF

      delegate_to: access_machine #specify which host to copy to
      ignore_errors: yes #ignore errors since some variables might not be applicable

    - name: save job info in a file
      lineinfile:
        path: "$HOME/ansible-backups/job-{{ awx_job_id }}"
        line: "workflow_jobname: {{ awx_workflow_job_name }}"
        insertbefore: BOF

      delegate_to: access_machine #specify which host to copy to
      ignore_errors: yes #ignore errors since some variables might not be applicable

    - name: save job info in a file
      lineinfile:
        path: "$HOME/ansible-backups/job-{{ awx_job_id }}"
        line: "inventory_id: {{ awx_inventory_id }}"
        insertbefore: BOF

      delegate_to: access_machine #specify which host to copy to
      ignore_errors: yes #ignore errors since some variables might not be applicable

    - name: save job info in a file
      lineinfile:
        path: "$HOME/ansible-backups/job-{{ awx_job_id }}"
        line: "inventory_name: {{ awx_inventory_name }}"
        insertbefore: BOF

      delegate_to: access_machine #specify which host to copy to
      ignore_errors: yes #ignore errors since some variables might not be applicable
